dist/browser-connector.js, dist/node-connector.js, src/mapd-con-es6.js, test/integration.spec.js
=> Wrap methods to reset thrift client on bad args

dist/browser-connector.js, dist/node-connector.js, src/mapd-client-v2.js, src/mapd-con-es6.js, src/typedefs.js, test/mapd-client-v2.unit.spec.js
No thrift changes, just a bug fix and a new function.
=> various connector updates (get_tables_meta, bug fixes)

dist/browser-connector.js, dist/node-connector.js, package.json, src/process-columnar-results.js, src/process-row-results.js, src/typedefs.js, yarn.lock
Adds support to `connector` for TINYINT queries and column types for use with `immerse`
Related to https://github.com/mapd/mapd-immerse/pull/4809
=> add support for TINYINT

dist/browser-connector.js, dist/node-connector.js, src/helpers.js, src/process-columnar-results.js, src/process-row-results.js, src/utils.js
Reverts mapd/mapd-connector#105
I merged this before it went to QA because it's Thursday and I can't think straight. Reverting it, then creating a new PR I guess?
=> Revert "Properly handle timestamps with precision >0"

dist/browser-connector.js, dist/node-connector.js, src/mapd-con-es6.js
Related to fix for https://jira.omnisci.com/browse/FE-7466 in Immerse
=> Add invalid session detection and automatic reconnect (single attempt) upon detecting

package.json
Preparing release 4.4, will tag and publish resulting master merge.
=> Bump package version to 4.4.0

dist/browser-connector.js, dist/node-connector.js, src/mapd-con-es6.js
Add basic client method wrapper (promise-based and errors handled) for `import_table_status` Thrift method, importTableStatusAsync.
=> [FE-4996] Add importTableStatusAsync method

dist/browser-connector.js, dist/node-connector.js, src/mapd-con-es6.js
Check for "User should re-authenticate." timeout error message too, in isTimeoutError for handleErrors
=> [FE-4902] Add another timeout message to isTimeoutError check

dist/browser-connector.js, dist/node-connector.js, src/mapd-con-es6.js
moves this._numConnections to initClients vs connect, so stuff works with SAML
=> fix num connections for init vs connect

dist/browser-connector.js, dist/node-connector.js, src/helpers.js, src/process-columnar-results.js, src/process-row-results.js, test/integration.spec.js
This reverts commit 957ba94b86f2863bfb6e528ac844363769e79966.
https://jira.omnisci.com/browse/FE-8304
=> Revert "[FE-5318] ensure float precision matches mapdql/core (#121)"

dist/browser-connector.js, dist/node-connector.js, src/mapd-con-es6.js, test/integration.spec.js
This is needed for https://github.com/omnisci/mapd-immerse/pull/5371 to work.
=> [FE-8324] - Adds descriptor fields to return from getFields()

dist/browser-connector.js, dist/node-connector.js, src/mapd-con-es6.js
Improve error handling for getFields call to cover case of unknown error from callback, as well as row_desc being undefined (shouldn't happen).
- Fixes #15 
- Fixes [FE-8233](https://jira.omnisci.com/browse/FE-8233)
=> [FE-8233] Improve error handling in getFields

examples/browser.js
=> Update example to match data format

package.json
Bump version for OmniSci release 4.7.0 + associated Thrift changes
=> Bump package version to 4.7.0

.travis.yml
https://benlimmer.com/2019/01/14/travis-ci-xvfb/
Verification: PR checks should pass here
=> [FE-9035] Update .travis.yml for breaking Travis change with xvfb

dist/browser-connector.js, dist/node-connector.js, src/mapd-con-es6.js
=> Removes reconnection attempts on errors since we have sessions now

dist/browser-connector.js, dist/node-connector.js, src/mapd-con-es6.js
Companion Immerse PR: https://github.com/omnisci/mapd-immerse/pull/6193
=> adds method-called event to emitter for bumping session timeouts

package-lock.json, package.json
=> [FE-10408] Dependency updates via `npm audit fix`

dist/browser-connector.js, dist/node-connector.js, package-lock.json, package.json, src/mapd-con-es6.js
[ramda's clone is fairly inefficient](https://github.com/ramda/ramda/issues/2134), so I swapped it out for lodash's cloneDeep. In my test, on a dashboard with 15 charts, total time spent cloning went from ~320ms to ~81ms during dashboard load.
=> [FE-12312] :zap: swap lodash's cloneDeep for ramda's clone

examples/node.js
Node.js example needed to be updated to use the new import/export conventions.
=> Update node.js example

dist/browser-connector.js, dist/node-connector.js, src/mapd-con-es6.js
Nuke the promise cache.
Ensures that non-object nonces are not passed through JSON.stringify.
=> [FE-12893][FE-12834] promise cache / nonce format

dist/browser-connector.js, dist/node-connector.js, src/mapd-con-es6.js
Simple PR to log arrow queries when logging is enabled.
=> [FE-13782] log arrow queries

dist/browser-connector.js, dist/node-connector.js, src/mapd-con-es6.js
Adds four new functions for interacting with the custom expressions api.
=> [FE-13553] add custom expression api

dist/browser-connector.js, dist/node-connector.js, thrift/OmniSci.js, thrift/extension_functions_types.js, thrift/omnisci_types.js
updated thrift for custom expression api changes
=> [FE-13553] updated thrift

dist/browser-connector.js, dist/node-connector.js, src/mapd-con-es6.js, thrift/OmniSci.js
=> [FE-14410] add getAllEffectiveRolesForUserAsync

dist/browser-connector.js, dist/node-connector.js, src/mapd-con-es6.js
Needed to retrieve a table's "most recent modification" timestamp
=> Add call for thrift method get_table_epoch_by_name

dist/browser-connector.js, dist/node-connector.js, package-lock.json, package.json, src/mapd-con-es6.js, src/process-query-results.js
Adds support for communicating via the thrift binary protocol.
=> [FE-14735] binary thrift support

dist/browser-connector.js, dist/node-connector.js, src/mapd-con-es6.js
=> [FE-14773] fix bug with arrow + binary thrift

dist/browser-connector.js, dist/node-connector.js, src/mapd-con-es6.js, test/process-columnar-results.unit.spec.js
=> [FE-14772] - Added data type mappers for initial FSI

dist/browser-connector.js, dist/node-connector.js, examples/browser.html, package-lock.json, package.json, src/heavy-con-es6.js
=> [FE-15300] update arrow

dist/browser-connector.js, dist/node-connector.js, src/heavy-con-es6.js
Needed for https://heavyai.atlassian.net/browse/FE-15707
Immerse PR: https://github.com/heavyai/immerse/pull/8614
=> [FE-15707] - Handles new thrift invalid session message

dist/browser-connector.js, dist/node-connector.js, src/process-columnar-results.js, src/process-row-results.js, src/typedefs.js, test/integration.spec.js, thrift/Heavy.js, thrift/common_types.js, thrift/extension_functions_types.js, thrift/heavy_types.js, thrift/serialized_result_set_types.js
Closes https://heavyai.atlassian.net/browse/FE-16289
Companion Immerse PR: https://github.com/heavyai/immerse/pull/8775
=> [FE-16289] - fixes use of MULTILINESTRING columns in SQL Editor
